# Window appearance
hide_window_decorations yes
window_border_width 0
background_opacity 0.8
dynamic_background_opacity false
blur 5
window_margin_width 0
window_padding_width 12
adjust_line_height 0
adjust_column_width 0

# Font
font_family CaskaydiaMono Nerd Font
font_size 11.0

# Cursor
cursor_shape block
cursor_shape_unfocused hollow
cursor_stop_blinking_after 0
cursor_trail 2
cursor_trail_decay 0.2 0.4
cursor_blink_interval 0.5

# Shell
shell_integration disabled

# Scrollback
scrollback_lines 10000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
wheel_scroll_multiplier 3
touch_scroll_multiplier 3

# Mouse
mouse_hide_wait 3.0
click_interval -1.0
focus_follows_mouse no

# Terminal
term xterm-256color
strip_trailing_spaces smart
copy_on_select clipboard
select_by_word_characters @-./_~?&=%+#

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Bell
bell_on_tab yes
visual_bell_duration 0.0
enable_audio_bell no

# Tab bar
enable_tab_bar yes
tab_bar_edge bottom
tab_bar_align left
tab_bar_margin_width 4
tab_bar_margin_height 5 2
tab_bar_style fade
tab_fade 0.25 0.5 0.75 1
tab_separator " ▎"
tab_title_template " {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}:  {title[title.rfind('/')+1:]} "
tab_bar_min_tabs 1
active_tab_font_style bold-italic
inactive_tab_font_style normal

# Tab management keybindings
map ctrl+shift+t         new_tab_with_cwd
map ctrl+shift+w         close_tab
map ctrl+shift+l         next_layout
map ctrl+shift+page_down move_tab_forward
map ctrl+shift+page_up   move_tab_backward
map ctrl+shift+]         next_tab
map ctrl+shift+[         previous_tab
map super+,              move_tab_forward
map super+\              move_tab_backward
map shift+super+]        next_tab
map shift+super+[        previous_tab
map ctrl+tab             noop

# Window management keybindings
map ctrl+shift+n         new_os_window_with_cwd
map ctrl+shift+enter     launch --location vsplit --cwd=current
map super+w              close_window
map alt+right            next_window
map alt+down             next_window
map alt+left             previous_window
map alt+up               previous_window
map ctrl+shift+f         move_window_forward
map ctrl+shift+b         move_window_backward
map ctrl+shift+`         move_window_to_top
map ctrl+shift+1         first_window
map ctrl+shift+2         second_window
map ctrl+shift+3         third_window
map ctrl+shift+4         fourth_window
map ctrl+shift+5         fifth_window
map ctrl+shift+6         sixth_window
map ctrl+shift+7         seventh_window
map ctrl+shift+8         eighth_window
map ctrl+shift+9         ninth_window
map ctrl+shift+0         tenth_window

# Theme
include themes/hackerman.conf
