vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
	vim.cmd("syntax reset")
end

vim.g.colors_name = "elflord_custom"
vim.o.background = "dark"
vim.o.termguicolors = true

local c = {
	bg = "#061a1a",
	bg_alt = "#082323",
	bg_soft = "#0d2c2c",
	bg_float = "#0b2525",
	fg = "#8ffcff",
	fg_dim = "#60c8cb",
	fg_soft = "#b5ffff",
	comment = "#8aa6a6",
	muted = "#4d7070",
	line = "#123838",
	selection = "#164849",
	cyan = "#8ffcff",
	cyan_bright = "#b9ffff",
	red = "#ff6b6b",
	func = "#d98b8b",
	red_dark = "#3a1416",
	orange = "#ffb86c",
	yellow = "#f1fa8c",
	green = "#7ee787",
	blue = "#82aaff",
	purple = "#c792ea",
}

local hl = {
	Normal = { fg = c.fg, bg = c.bg },
	NormalNC = { fg = c.fg_dim, bg = c.bg },
	Cursor = { fg = c.bg, bg = c.red },
	CursorIM = { fg = c.bg, bg = c.red },
	lCursor = { fg = c.bg, bg = c.red },
	NormalFloat = { fg = c.fg, bg = c.bg_float },
	FloatBorder = { fg = c.muted, bg = c.bg_float },
	FloatTitle = { fg = c.cyan_bright, bg = c.bg_float, bold = true },
	SignColumn = { fg = c.muted, bg = c.bg },
	FoldColumn = { fg = c.muted, bg = c.bg },
	Folded = { fg = c.fg_dim, bg = c.bg_soft },
	ColorColumn = { bg = c.bg_alt },
	CursorLine = { bg = c.bg_alt },
	CursorColumn = { bg = c.bg_alt },
	CursorLineNr = { fg = c.orange, bg = c.bg_alt, bold = true },
	LineNr = { fg = c.muted },
	WinSeparator = { fg = c.line, bg = c.bg },
	VertSplit = { fg = c.line, bg = c.bg },
	StatusLine = { fg = c.bg, bg = c.cyan, bold = true },
	StatusLineNC = { fg = c.fg_dim, bg = c.bg_soft },
	TabLine = { fg = c.fg_dim, bg = c.bg_soft },
	TabLineFill = { bg = c.bg },
	TabLineSel = { fg = c.bg, bg = c.cyan, bold = true },
	Pmenu = { fg = c.fg, bg = c.bg_soft },
	PmenuSel = { fg = c.bg, bg = c.cyan, bold = true },
	PmenuSbar = { bg = c.bg_alt },
	PmenuThumb = { bg = c.muted },
	WildMenu = { fg = c.bg, bg = c.cyan, bold = true },
	Visual = { bg = c.selection },
	VisualNOS = { bg = c.selection },
	Search = { fg = c.bg, bg = c.yellow },
	IncSearch = { fg = c.bg, bg = c.orange },
	CurSearch = { fg = c.bg, bg = c.orange, bold = true },
	MatchParen = { fg = c.yellow, bg = c.bg_soft, bold = true },
	Directory = { fg = c.cyan_bright, bold = true },
	Title = { fg = c.cyan_bright, bold = true },
	Question = { fg = c.green },
	MoreMsg = { fg = c.green },
	ModeMsg = { fg = c.fg_soft },
	NonText = { fg = c.muted },
	SpecialKey = { fg = c.muted },
	Whitespace = { fg = c.muted },
	EndOfBuffer = { fg = c.bg },

	Comment = { fg = c.comment, italic = true },
	Constant = { fg = c.cyan_bright },
	String = { fg = c.green },
	Character = { fg = c.green },
	Number = { fg = c.orange },
	Boolean = { fg = c.orange, bold = true },
	Float = { fg = c.orange },
	Identifier = { fg = c.fg },
	Function = { fg = c.func },
	Statement = { fg = c.cyan, bold = true },
	Conditional = { fg = c.red, bold = true },
	Repeat = { fg = c.red, bold = true },
	Label = { fg = c.cyan },
	Operator = { fg = c.red },
	Keyword = { fg = c.red, bold = true },
	Exception = { fg = c.red },
	PreProc = { fg = c.purple },
	Include = { fg = c.purple },
	Define = { fg = c.purple },
	Macro = { fg = c.purple },
	PreCondit = { fg = c.purple },
	Type = { fg = c.red, bold = true },
	StorageClass = { fg = c.red },
	Structure = { fg = c.red },
	Typedef = { fg = c.red },
	Special = { fg = c.cyan_bright },
	SpecialChar = { fg = c.yellow },
	Tag = { fg = c.cyan },
	Delimiter = { fg = c.fg_dim },
	SpecialComment = { fg = c.comment, bold = true },
	Debug = { fg = c.orange },
	Underlined = { fg = c.blue, underline = true },
	Ignore = { fg = c.muted },
	Error = { fg = c.red, bg = c.red_dark, bold = true },
	Todo = { fg = c.bg, bg = c.yellow, bold = true },

	DiffAdd = { fg = c.green, bg = "#12311f" },
	DiffChange = { fg = c.yellow, bg = "#34320f" },
	DiffDelete = { fg = c.red, bg = c.red_dark },
	DiffText = { fg = c.bg, bg = c.orange, bold = true },
	Added = { fg = c.green },
	Changed = { fg = c.yellow },
	Removed = { fg = c.red },

	DiagnosticError = { fg = c.red },
	DiagnosticWarn = { fg = c.orange },
	DiagnosticInfo = { fg = c.cyan },
	DiagnosticHint = { fg = c.green },
	DiagnosticOk = { fg = c.green },
	DiagnosticUnderlineError = { sp = c.red, undercurl = true },
	DiagnosticUnderlineWarn = { sp = c.orange, undercurl = true },
	DiagnosticUnderlineInfo = { sp = c.cyan, undercurl = true },
	DiagnosticUnderlineHint = { sp = c.green, undercurl = true },
	DiagnosticVirtualTextError = { fg = c.red, bg = c.red_dark },
	DiagnosticVirtualTextWarn = { fg = c.orange, bg = "#33250d" },
	DiagnosticVirtualTextInfo = { fg = c.cyan, bg = c.bg_soft },
	DiagnosticVirtualTextHint = { fg = c.green, bg = "#12311f" },
	LspReferenceText = { bg = c.bg_soft },
	LspReferenceRead = { bg = c.bg_soft },
	LspReferenceWrite = { bg = c.bg_soft, underline = true },

	["@variable"] = { fg = c.fg },
	["@variable.builtin"] = { fg = c.cyan_bright, italic = true },
	["@variable.parameter"] = { fg = c.fg_soft },
	["@constant"] = { fg = c.cyan_bright },
	["@constant.builtin"] = { fg = c.orange, bold = true },
	["@module"] = { fg = c.purple },
	["@label"] = { fg = c.cyan },
	["@string"] = { fg = c.green },
	["@character"] = { fg = c.green },
	["@number"] = { fg = c.orange },
	["@boolean"] = { fg = c.orange, bold = true },
	["@function"] = { fg = c.func },
	["@function.builtin"] = { fg = c.func },
	["@function.call"] = { fg = c.func },
	["@constructor"] = { fg = c.func },
	["@keyword"] = { fg = c.red, bold = true },
	["@keyword.function"] = { fg = c.red, bold = true },
	["@keyword.operator"] = { fg = c.red },
	["@operator"] = { fg = c.red },
	["@type"] = { fg = c.red },
	["@type.builtin"] = { fg = c.red, bold = true },
	["@property"] = { fg = c.cyan_bright },
	["@field"] = { fg = c.cyan_bright },
	["@punctuation"] = { fg = c.fg_dim },
	["@punctuation.bracket"] = { fg = c.fg_dim },
	["@punctuation.delimiter"] = { fg = c.fg_dim },
	["@comment"] = { fg = c.comment, italic = true },
	["@tag"] = { fg = c.red },
	["@tag.attribute"] = { fg = c.cyan_bright },
	["@tag.delimiter"] = { fg = c.fg_dim },
	["@lsp.type.parameter"] = { fg = c.fg_soft },
	["@lsp.type.function"] = { fg = c.func },
	["@lsp.type.type"] = { fg = c.red },
	["@lsp.type.variable"] = { fg = c.fg },

	CmpItemAbbr = { fg = c.fg },
	CmpItemAbbrDeprecated = { fg = c.muted, strikethrough = true },
	CmpItemAbbrMatch = { fg = c.cyan_bright, bold = true },
	CmpItemAbbrMatchFuzzy = { fg = c.cyan_bright, bold = true },
	CmpItemKind = { fg = c.red },
	CmpItemMenu = { fg = c.comment },

	TelescopeNormal = { fg = c.fg, bg = c.bg },
	TelescopeBorder = { fg = c.line, bg = c.bg },
	TelescopePromptNormal = { fg = c.fg, bg = c.bg_soft },
	TelescopePromptBorder = { fg = c.bg_soft, bg = c.bg_soft },
	TelescopePromptTitle = { fg = c.bg, bg = c.red, bold = true },
	TelescopePreviewTitle = { fg = c.bg, bg = c.cyan, bold = true },
	TelescopeResultsTitle = { fg = c.bg, bg = c.purple, bold = true },
	TelescopeSelection = { fg = c.cyan_bright, bg = c.bg_soft, bold = true },
	TelescopeMatching = { fg = c.orange, bold = true },

	NeoTreeNormal = { fg = c.fg, bg = c.bg },
	NeoTreeNormalNC = { fg = c.fg_dim, bg = c.bg },
	NeoTreeDirectoryName = { fg = c.cyan_bright },
	NeoTreeDirectoryIcon = { fg = c.cyan },
	NeoTreeFileName = { fg = c.fg },
	NeoTreeFileNameOpened = { fg = c.cyan_bright, bold = true },
	NeoTreeGitAdded = { fg = c.green },
	NeoTreeGitModified = { fg = c.yellow },
	NeoTreeGitDeleted = { fg = c.red },
	NeoTreeIndentMarker = { fg = c.muted },
}

for group, opts in pairs(hl) do
	vim.api.nvim_set_hl(0, group, opts)
end

local links = {
	qfLineNr = "LineNr",
	qfFileName = "Directory",
	Substitute = "Search",
	MsgArea = "Normal",
	MsgSeparator = "WinSeparator",
	FloatShadow = "NormalFloat",
	FloatShadowThrough = "NormalFloat",
	WinBar = "StatusLineNC",
	WinBarNC = "StatusLineNC",
	SpellBad = "DiagnosticUnderlineError",
	SpellCap = "DiagnosticUnderlineWarn",
	SpellRare = "DiagnosticUnderlineInfo",
	SpellLocal = "DiagnosticUnderlineHint",
}

for from, to in pairs(links) do
	vim.api.nvim_set_hl(0, from, { link = to })
end

vim.cmd("syntax enable")
vim.cmd("filetype plugin on")
