source = /home/amrxtgh/.config/hypr/current_theme.conf
general {
  ignore_empty_input = true
  no_fade_in = true
  disable_loading_bar = true
}

input-field {
    monitor =
    size = 520, 72
    position = 0, 10
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4
    shadow_passes = 2
    shadow_size = 6
    shadow_color = $shadow_color

    font_family = JetBrainsMono Nerd Font
    font_color = rgba(235, 235, 235, 0.95)

    placeholder_text = Enter password
    placeholder_color = $font_color
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    fade_on_empty = false
}

label {
  text = $LAYOUT
  font_family = Adwaita Sans
  shadow_passes = 1
  shadow_size = 2

  position = 0, -80
  halign = center
  valign = center
}

background {
  monitor =
  path = /home/amrxtgh/Downloads/pics/wallpaper.jpg
  blur_passes = 3
  blur_size = 6
  brightness = 0.7
  contrast = 1.0
}

animations {
    enabled = false
}
