# Theme - lovely (from alacritty)
foreground #9dd9de
background #00181d

selection_foreground #00181d
selection_background #58c8d0

cursor #71e6ee
cursor_text_color #00181d

# Black
color0 #00262d
color8 #0a3a44

# Red
color1 #e06c75
color9 #ff8b94

# Green
color2 #8bcf7a
color10 #b6f08d

# Yellow
color3 #c8d872
color11 #e4f17a

# Blue
color4 #6ec1ff
color12 #8fd5ff

# Magenta
color5 #c792ea
color13 #ddb2ff

# Cyan
color6 #4fd7de
color14 #7deaf0

# White
color7 #bde7ea
color15 #e3fbff
