# Idle manager / screen lock
exec-once = uwsm app -- hypridle

# Notification daemon
exec-once = uwsm app -- mako

# Status bar
exec-once = uwsm app -- waybar

# Input method (optional)
exec-once = uwsm app -- fcitx5

# Set wallpaper
exec-once = uwsm app -- swaybg -i ~/.config/hypr/background.png -m fill

# On-screen display
exec-once = uwsm app -- swayosd-server

# PolicyKit agent (for admin prompts)
exec-once = uwsm app -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Clipboard manager
exec-once = uwsm app -- wl-clip-persist --clipboard regular --all-mime-type-regex '^(?!x-kde-passwordManagerHint).+'

